### PR TITLE
Print & exit if only installed pkgs

### LINKED ISSUE #29: moss creates an empty transaction if attempting to install an already installed package
Expected behaviour:

```
root@sosroot # ~ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Serpent OS borkytests (fstx #4)"
root@sosroot # ~ moss li |grep neofetch
 neofetch                 7.1.0-2 - Command-line system information tool
root@sosroot # ~ moss it neofetch
package neofetch is already installed, exiting.
root@sosroot # ~ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Serpent OS borkytests (fstx #4)"
```

Observed behaviour:

```
root@sosroot # ~ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Serpent OS borkytests (fstx #4)"
root@sosroot # ~ moss li |grep neofetch
 neofetch                 7.1.0-2 - Command-line system information tool
root@sosroot # ~ moss it neofetch
The following packages will be installed


Do you want to continue? [ Yes / No ] Y
 
 Blitting filesystem
 ◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼  100% 23208 of 23208 entries
root@sosroot # ~ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Serpent OS borkytests (fstx #5)"
root@sosroot # ~ 
```

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #29 

Currently `install` doesn't check if final transaction state is comprised of only "installed" packages. This fixes the issue by only applying the transaction if there's >=1 package not currently installed.

If no new packages exist, the list of user provided packages already installed will be printed and exit.

As seen below, if user provides both installed & uninstalled packages, it'll only list new packages and carry on w/ the transaction. If user provides only installed packages, it'll print them and exit.

image

### CODE REVIEW

File: source/moss/client/cli/install.d [hunk 1]
```diff
@@ -17,17 +17,18 @@ module moss.client.cli.install;
...
 import std.experimental.logger;
+import std.file : exists;
 import std.range : empty;
+import std.stdio : writefln, writef, writeln;
 import std.string : join, wrap, format, endsWith;
-import std.algorithm : map, filter;
-import moss.client.ui;
-import moss.client.statedb;
-import moss.client.cli : MossCLI;
-import std.file : exists;
```
Comment (tarkah) [inline source/moss/client/cli/install.d:30]: I've sorted imports, but I can disregard in the future

**Review by ermo — APPROVED** [review]
Thank you for sorting imports.

LGTM, thanks!
